### PR TITLE
Add Blue Line to README.md

### PR DESCRIPTION
**Pull request by nekodjin**
Correct the README to reflect that a Blue Line tracker has been added to the app.

### CODE REVIEW

**Review by devinmatte — COMMENTED** [review]
Thanks for making a PR! I think this whole sentence could use a rewrite as we show new Orange, Red and Green line cars, and we additional show Blue line cars, but there are no "new" blue line cars to show or track. If you want to take a crack at rewriting this to be more clear on that point that would be great

**Comment by mathcolo** [comment]
@nekodjin That would work! Could you make that change to your branch?

**Comment by nekodjin** [comment]
On it by tomorrow :)

**Comment by nathan-weinberg** [comment]
@nekodjin Hey! We'd still be interested in getting that change in if you can make the suggested update :smile:

**Comment by nathan-weinberg** [comment]
Since this seems to be abandoned I'm going to close this for now - @nekodjin if you're able to come back around and update your branch feel free to reopen it!

**Pull request closed without merging**
