### PR TITLE
feat: show googly eyes 👀

### PR DESCRIPTION
**Pull request by rudiejd**
## Motivation

👀show the trains with googly eyes

https://apnews.com/article/boston-subway-trains-googly-eyes-42c69329096151eba01dc5b31f34fedc 

## Changes

image

## Testing Instructions
Look at trains and verify that the cars with confirmed googly eyes show up with the eyes emoji. Let me know if there are any other cars I can add!

### CODE REVIEW

**Comment by devinmatte** [comment]
Screenshot 2024-07-09 at 9 10 05 PM

It would still be good to see the direction of the train still, so maybe we can do something like this where we show the googly eyes off to the side in the top right pill. That way we don't need a new tab for it and can show it on all the tabs

**Comment by rudiejd** [comment]
@devinmatte I like that idea! I still think the tab should be here though, since there are so few of these cars that they can get lost on the default views. Let me try rendering a pill

**Comment by rudiejd** [comment]
how does this look? I could pick a different color but you get the idea

image

**Comment by devinmatte** [comment]
That's solid, that's what I was thinking

**Pull request merged**
