### PR TITLE
Moved README to docs and Playbook to devops

### PR DESCRIPTION
**Pull request by nathan-weinberg**
T4R

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
Also not sure if we want to add a LICENSE similar to [the one in the Data Dashboard repo?](https://github.com/transitmatters/t-performance-dash/blob/main/LICENSE)

**Review by idreyn — APPROVED** [review]
LGTM! We definitely should add a license too

**Comment by nathan-weinberg** [comment]
Cool, what kind of License? I can just add it as part of this PR

**Review by mathcolo — APPROVED** [review]
Same as the dashboard maybe?

**Comment by nathan-weinberg** [comment]
Done!

**Pull request merged**
