### PR TITLE
GLX stops, Medford Branch

### PR DESCRIPTION
**Pull request by devinmatte**
The place ids are placeholders are the mbta API doesn't seem to yet have the new stations listed as available. 
Due to the lines being at the opposite end, I had to do some adjustments with curves before the shared stops to deal with the new D branch. No idea if this is how mantainers would want this to be, but thought this was a good starting point.

Relates to #58 

Screen Shot 2022-07-31 at 5 14 35 PM

### CODE REVIEW

**Comment by idreyn** [comment]
Hi Devin, thanks for the PR! We have been talking about doing this _forever_ so I appreciate you getting a jump on this as GLX approaches. I think we'll want to deploy this in two stages:

- One to add the Science Park, Lechmere, and Union segment opening in March. We were thinking of putting the Union stop on the same straight line as the GL trunk for simplicity's sake. It could also dip out a bit the same way the rest of the branches do, but the line should be running vertically at Union so the station can be labelled properly.
- Another to add the Medford branch, scheduled for May (but probably opening later). Our plan is to have this branch dip to the right of the trunk with a `wiggle()`. Together the two branches would look like this (apologies for the worst mockup you've ever seen):

image

Would you be amenable to implementing this? We could launch early with both new segments if we find a way to make it clear that they're not open yet (opacity or dotted lines?) or we can trickle them out as they come online.

Thanks again for your work on this!

**Comment by mathcolo** [comment]
Hey Devin, any updates on this? Union branch is getting close, and we're looking forward to seeing your changes 😃

**Comment by devinmatte** [comment]
@mathcolo Sorry I've been out of the country so I haven't had a chance to do this. I'll plan to update it next week as I arrive back tomorrow. However if someone else wishes to take over sooner I understand. I'm adding time to my calendar now to look at it

**Comment by mathcolo** [comment]
@devinmatte Sounds good! Just wanted to make sure you still had it on your mind since we're close to the opening. Keep us posted if you need us to take over 👍

**Comment by devinmatte** [comment]
Screen Shot 2022-03-13 at 9 10 26 PM
👋 I just got this working as designed above. Should have the PR updated tonight. Going to play around with dashed lines and see if the mbta api has proper labels yet

**Comment by devinmatte** [comment]
So I'm currently unable to understand why Lechmere doesn't show a label despite the API returning a stop name for it, and it being in the labeled list. Maybe there's some code I've missed, but the attached image from above is what I'm able to get with the current state of the PR

**Comment by idreyn** [comment]
When I checked just now, Lechmere and Science Park are still missing from the API:
```
https://api-v3.mbta.com/stops?filter[route]=Green-E
```
So I think we gotta give it a few more days before they come back online and get labels. This is looking great, though! Between now and Monday, if you get the dashed lines working, I think we can launch this. Otherwise let's cut the Medford branch out for now and add Science Park, Lechmere, and Union to the trunk.

**Comment by devinmatte** [comment]
I'll split this into two PRs since it looks like dashed lines are more complicated than I have time to dedicate to this

**Comment by idreyn** [comment]
Will you be able to get a PR for the Union branch out today? No worries either way.

**Comment by devinmatte** [comment]
Yep, I was planning to split this this afternoon. Sorry for the delay

**Comment by devinmatte** [comment]
I see there was already a commit made, sorry I didn't get to this. I'll make sure this PR is fully ready to merge day 0 for the remaining stops

**Comment by nathan-weinberg** [comment]
I feel like Medford branch should be the main one and Union should wiggle off? Similar to the map they have posted in some of the trolleys
image

**Comment by devinmatte** [comment]
Waiting for real API place names, but marking ready for review in the meantime

**Comment by nathan-weinberg** [comment]
Still thinking Union should be a stub and Medford should continue straight

**Comment by idreyn** [comment]
> Waiting for real API place names, but marking ready for review in the meantime

Reposting this from Slack with the new station IDs: https://github.com/mbta/api/pull/518/files

> Still thinking Union should be a stub and Medford should continue straight

I'm in favor of this with a potential caveat: our map of the GL network is already fairly wide, and the four southern branches fan out to take up essentially the entire viewport of small phones. So we should avoid making the bounding box of the entire system wider or it will get cut off. Since the trunk is currently continues on to the C branch, we can mirror the curve of the B branch on the north side to create the Union stub:

image

But, we will want to fit the station label in a box to the _right_ of the station, in the cramped space indicated by the white rectangle above. So we may have to abbreviate it to `Union` instead of `Union Square` — which I think is absolutely fine.

**Review by mathcolo — APPROVED** [review]

**Pull request merged**
